// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN0J4H4c5l93eaVTcpc6xEO69GYh-8vm4',
    appId: '1:634339112333:web:ac0d9f411ef2f9cd4b79c4',
    messagingSenderId: '634339112333',
    projectId: 'farmingo-bd834',
    authDomain: 'farmingo-bd834.firebaseapp.com',
    storageBucket: 'farmingo-bd834.appspot.com',
    measurementId: 'G-NHBK55H9EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQAeE1i06abOqwiT9JVv2ZVEFOTA8BmJw',
    appId: '1:634339112333:android:4e27878a329c96fb4b79c4',
    messagingSenderId: '634339112333',
    projectId: 'farmingo-bd834',
    storageBucket: 'farmingo-bd834.appspot.com',
  );
}
